<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
	<title><?= __('maintence title') ?></title>
	<?= Cms_Packer::css(md5('xxx'), array());
	?>

</head>

<body class="nifty-ready mar-no pace-done">
<div id="container" class="cls-container">
	<div class="cls-content">
		<h1 class="error-code text-warning"><?= __('maintence title') ?></h1>
	</div>
</body>
</html>
