<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><?= __('Users') ?></h1>
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<span><?= __('users:list') ?></span>
					<div class="pull-right col-sm-1">
						<UIButton action-action="load|roles,new" caption="<?= __('new role') ?>"
						          classnames="btn-success btn-xs"></UIButton>
					</div>

					<div class="pull-right col-sm-1">
						<UIButton action-action="reload" caption="<?= __('reload data') ?>"
						          classnames="btn-success btn-xs"></UIButton>
					</div>
				</div>
				<!-- /.panel-heading -->
				<div class="panel-body">
					<div class="dataTable_wrapper">
						<Roles></Roles>
					</div>
					<!-- /.table-responsive -->
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel -->
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
</div>