<div class="table-responsive">
	<table class="table table-striped table-bordered"  id="js-rolesList">
		<thead>
		<tr>
			<th>#</th>
			<th><?= __('name') ?></th>
			<th><?= __('desc') ?></th>
			<th><?= __('is owner') ?></th>
			<th><?= __('actions') ?></th>
		</tr>
		</thead>
		<tbody>
		<? foreach ($this->all as $row): ?>
			<tr>
				<td><?= $row->id ?></td>
				<td contenteditable="true" id="js-name-<?= $row->id ?>"><?= $row->name ?></td>
				<td contenteditable="true" id="js-desc-<?= $row->id ?>"><?= $row->description ?></td>
				<td><?= $row->is_owner == 1 ? __('Yes') : __('No') ?></td>
				<td>
					<EventListener action-click="permissions|<?= $row->id ?>">
						<a data-toggle="tooltip" data-placement="top" title="<?= __('permissions') ?>"
						   href="javascript:void(0)"><i class="fa fa-key fa-fw"></i></a>
					</EventListener>
					<EventListener action-click="save|<?= $row->id ?>">
						<a data-toggle="tooltip" data-placement="top" title="<?= __('save user') ?>"
						   href="javascript:void(0)"><i class="fa fa-check fa-fw"></i></a>
					</EventListener>
					<EventListener action-click="delete|<?= $row->id ?>">
						<a data-toggle="tooltip" data-placement="top" title="<?= __('delete user') ?>"
						   href="javascript:void(0)"><i class="fa fa-trash-o fa-fw"></i></a>
					</EventListener>
				</td>
			</tr>
		<? endforeach ?>
		</tbody>
	</table>
</div>