<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"><?= __('Roles') ?></h1>
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<span><?= __('roles:add') ?></span>

					<div class="pull-right col-sm-1">
						<UIButton action-action="load|roles,index" caption="<?= __('roles list') ?>"
						          classnames="btn-success btn-xs"></UIButton>
					</div>
				</div>
				<!-- /.panel-heading -->
				<div class="panel-body">
					<div class="form-group">
						<label><?= __('name') ?></label>
						<input class="form-control" id="js-name">
					</div>

					<div class="form-group">
						<label><?= __('description') ?></label>
						<input class="form-control" id="js-desc">
					</div>

					<div class="form-group">
						<label><?= __('role permissions') ?></label>
						<div>
							<EventListener action-click="selectAll|permCheckbox">
								<span class="cursorP"><?= __('select all') ?></span>
							</EventListener>
							/
							<EventListener action-click="selectNone|permCheckbox">
								<span class="cursorP"><?= __('select none') ?></span>
							</EventListener>
						</div>
						<? foreach ($this->permissions as $perm_row): ?>
							<div class="checkbox">
								<label>
									<input class="permCheckbox" type="checkbox" value="<?= $perm_row->bit_flag ?>"><?= $perm_row->name ?>
								</label>
							</div>
						<? endforeach ?>
					</div>

					<UIButton action-action="addRole" caption="<?= __('add') ?>"
					          classnames="btn-success btn-lg"></UIButton>
				</div>
				<!-- /.panel-body -->
			</div>
			<!-- /.panel -->
		</div>
		<!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->
</div>